# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8519f86b5c30112972811ec065ee4457eb457eae5f416616d2e496500cf1ae6fb81d308e1cb670d41219f115e18b9e25e4402855b66e683aeacac1062da673d8

test:
  secret_key_base: 913ac016e05124eb33e1522276b0213da72b252ed06386ded845f80f089f6e8dd2aa761e0f9a655027c7bbe82d2a27eabf19b5c9594f59d5e14d9d667803882c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
